FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install python dependencies for training (pin transformers<4.45.0 to be compatible with PyTorch 2.1.0)
RUN pip install --no-cache-dir \
    "transformers<4.45.0" \
    datasets \
    seqeval \
    evaluate \
    accelerate \
    minio \
    arq \
    pydantic \
    pydantic-settings \
    mlflow-skinny==2.11.3 \
    boto3

# Copy application source code
COPY . /app

# Command to run ARQ Worker
CMD ["arq", "worker.worker.WorkerSettings"]
